highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:title.html
name: "熊猫文件"

author: "zyvv"
atom-baseurl: "zyvv.github.io"
#disqus: "gopherwood"

# navigations:
